project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "assignment_gretl.qmd"
    - "assignment_r.qmd"
#    - "AIrep/qmdrds/conv.qmd"

website:
  title: "OEKA201AssignmentKLBRHBAY"
left:
    - text: Home
      href: index.qmd
    - text: Bjørnar's assignment using Gretl
      href: assignment_gretl.qmd
    - text: Bjørnar's assignment using R
      href: assignment_r.qmd
right:
    - text: AI-conversation
#      href: AIrep/qmdrds/conv.qmd

format:
  html:
    toc: true
  docx:
    toc: true
  pdf:
    toc: true
  epub:
    toc: true

bibliography: ref.bib
